version: '3'
services:
  mpfrontend:
    depends_on:
      - mpserver
    image: "${USER}/mpfrontend:dev"
    build:
      context: mpfrontend/
    ports:
      - "8080:8080"
    volumes:
      - "./mpfrontend:/home/node/app"
  mpserver:
    depends_on:
      - redis
    image: "${USER}/mpserver:dev"
    build:
      context: mpserver/
    environment:
      - REDIS_URL=redis:6379
      - PORT=8081
      - GIN_MODE=release
    ports:
      - "8081:8081"
    volumes:
      - "./mpserver:/go/src/app"
  redis:
    image: "redis:alpine"
