version: '3'
services:
  mpfrontend:
    depends_on:
      - mpserver
    image: "aouyang1/mpfrontend:dev"
    build:
      context: mpfrontend
      dockerfile: Dockerfile_prod
    ports:
      - "8080:8080"
  mpserver:
    depends_on:
      - redis
    image: "aouyang1/mpserver:dev"
    build:
      context: mpserver/
      dockerfile: Dockerfile_prod
    environment:
      - REDIS_URL=redis:6379
      - PORT=8081
      - GIN_MODE=release
    ports:
      - "8081:8081"
    volumes:
      - "./mpserver/data:/go/src/app/data"
  redis:
    image: "redis:alpine"
