apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpfrontend-deployment
  labels:
    app: mpfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpfrontend
  template:
    metadata:
      labels:
        app: mpfrontend
    spec:
      containers:
      - name: mpfrontend
        image: aouyang1/mpfrontend:latest
        ports:
        - containerPort: 8080
