apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpserver-deployment
  labels:
    app: mpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpserver
  template:
    metadata:
      labels:
        app: mpserver
    spec:
      containers:
      - name: mpserver
        image: aouyang1/mpserver:latest
        ports:
        - containerPort: 8081
